### ISSUE TITLE
Foundation Height

### ISSUE THREAD

**Issue by ishakpilavci** [HydrologicEngineeringCenter/NSI#14]
How are the Found_Ht data measured? I observed that Found_Ht never takes the value 2 feet, is there a particular reason behind this? I also wonder whether there's a way to get First Floor Height (i.e. First Floor Elevation from the ground elevation) using Found_Ht (and/or other NSI fields)?

Thanks a lot!

**Comment by HenryGeorgist** [comment]
Foundation heights are assigned based on regionally defined distributions of foundation type and then distributions of height by foundation type at the occupancy type level for NSI V2. The foundation height is an approximation and should be reviewed and adjusted to reflect local information if available, we are always seeking to improve these fields if better methods or data exist of which you are aware.  See more here: [Structures With Improper Foundation Heights](https://www.hec.usace.army.mil/confluence/nsidocs/nsi-2019-frequently-asked-questions-54662577.html#NSI2019FrequentlyAskedQuestions-StructuresWithImproperFoundationHeights)

There is a ground elevation field in the NSI V2 data, if you combine that with foundation height you will get First Floor Elevation. FFE is useful when working with Water Surface Elevations, but the predominate use case in my experience is Depth data which would be depth above ground, so we tend to provide ground elevation and foundation height separately to support both use cases.
