### ISSUE TITLE
Server error while accessing the NSI database and Bounding Box Query

### ISSUE THREAD

**Issue by waqasiqbal123** [HydrologicEngineeringCenter/NSI#18]
Hi, 

I am trying to use the API of bounding box to get the data for specific county "Harford County, MD" . But i am getting the internal server error. Attached is the screenshot for the issue. I am using the "Structures by bounding box" and actually i am interested to get the NSI data for the above mentioned county so also please mention if I have to use some other code for getting the county data? 

Thanks 
Waqas

![image](https://user-images.githubusercontent.com/123578965/221916790-bb049a59-2a11-4b14-b230-67f2299f740b.png)

**Comment by HenryGeorgist** [comment]
can  you post your full url? i want to see how you formatted the bbox request

Alternatively if you want a whole county, use the fips endpoint. The fips code for harford county md = 24025

https://md.postcodebase.com/county/24025

**Comment by waqasiqbal123** [comment]
Thanks now i have used the FIPS id and fetched the data. Can you please guide that the data shown now in python window how we will be able to export this data as a geojson file ?

**Comment by HenryGeorgist** [comment]
so the return should be a feature collection in geojson format by default. Just write it to disk in a destination of your choosing and make the extension of the file .json. It should be recognized by any gis engine pretty much.
If you want to be sure it is a feature collection add the argument ```&fmt=fc``` as specified in the docs https://www.hec.usace.army.mil/confluence/nsi/technicalreferences/latest/api-reference-guide#id-.APIReferenceGuidev2022-GET

Example return from the default request with no format specification...
```json
{"type": "FeatureCollection","features":[{"type": "Feature","geometry": {"type": "Point","coordinates": [-156.983870, 21.188934]},"properties":{"fd_id":594360262,"bid":"73H552Q8+HFC-2-2-3-3","occtype":"RES5","st_damcat":"COM","bldgtype":"M","found_type":"I","cbfips":"150050319001015","pop2amu65":1,"pop2amo65":0,"pop2pmu65":20,"pop2pmo65":6,"sqft":69000,"num_story":1,"ftprntid":"15005_232","ftprntsrc":"Bing","students":0,"found_ht":8,"val_struct":9443706.3,"val_cont":4721853.15,"val_vehic":216000,"source":"X","med_yr_blt":1947,"firmzone":null,"o65disable":0.38,"u65disable":0,"x":-156.9838696,"y":21.188934226,"ground_elv":59.208809251708985,"ground_elv_m":18.046844482421875}}
...
```

**Comment by waqasiqbal123** [comment]
Thank you so much, but I have written the JSON file and that is not
supported or read by arcgis. Arcgis only accepts geojson and I am not sure
how I can i get the geojson from it.

This is my script to write the json file but it is not pretty much readable
by the arcgis:

import requests
import geojson
import pandas as pd
response=requests.get("
https://nsi.sec.usace.army.mil/nsiapi/structures?fips=24025")


response.json()
df=pd.DataFrame(response)

df. to_json("I:\DEEDS_DOD\Hazus_data_Folder _APG_Haz_Analysis\County.json")

**Comment by HenryGeorgist** [comment]
The response contents should be valid json. I think you might just write the bytes directly to disk as a string without creating a pandas dataframe and without calling to_json on the pandas dataframe.

**Comment by HenryGeorgist** [comment]
try
```python
import requests
response=requests.get("https://nsi.sec.usace.army.mil/nsiapi/structures?fips=24025")
with open("I:\DEEDS_DOD\Hazus_data_Folder _APG_Haz_Analysis\County.json", "w") as f:
    f.write(response.text)
```

**Comment by HenryGeorgist** [comment]
@waqasiqbal123 - did this address your issues? can this item be closed?

**Comment by waqasiqbal123** [comment]
Yes this solved my problem. Thank you so much for guiding through this. I
really appreciate your help..
